### ISSUE TITLE
"False cube! Color detection failed"

### ISSUE THREAD

**Issue by oguzsh** [HaginCodes/3x3x3-Image-processing#2]
# Problem
+ File :  SolveCube.java
+ Catch message : 
False cube! Color detection failed. Please retry
"java.lang.IndexOutOfBoundsException: Index: 265028, Size: 253440"

## Description
I tried many options but none one of them worked. How can I solve this problem?

## Error Message

> False cube! Color detection failed. Please retry
java.lang.IndexOutOfBoundsException: Index: 265028, Size: 253440
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at SolveCube.stageSolution(SolveCube.java:368)
	at SolveCube.solve(SolveCube.java:313)
	at SolveCube.solver(SolveCube.java:289)
	at SolveCube.mapOrientation(SolveCube.java:173)
	at AnalyzeFrame.getSolution(AnalyzeFrame.java:385)
	at AnalyzeFrame.make2dCube(AnalyzeFrame.java:376)
	at AnalyzeFrame.k_means(AnalyzeFrame.java:361)
	at AnalyzeFrame.findCenters(AnalyzeFrame.java:304)
	at AnalyzeFrame.changeThemColors(AnalyzeFrame.java:252)
	at AnalyzeFrame.determineToCaptureOrPass(AnalyzeFrame.java:146)
	at AnalyzeFrame.captureFrame(AnalyzeFrame.java:65)
	at VideoCap.getOneFrame(VideoCap.java:43)
	at MainFrame$2.keyPressed(MainFrame.java:74)
	at java.awt.Component.processKeyEvent(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

 > A fatal error has been detected by the Java Runtime Environment:

>   Internal Error (0xc000000d), pid=64532, tid=0x000000000000fc5c
>  JRE version: Java(TM) SE Runtime Environment (8.0_221-b11) (build 1.8.0_221-b11)
>  Java VM: Java HotSpot(TM) 64-Bit Server VM (25.221-b11 mixed mode windows-amd64 compressed oops)
>  Problematic frame:
>  C  [ntdll.dll+0x10f260]

>  Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
>  An error report file with more information is saved as:
>  D:\Users\pc\git\3x3x3-Rubiks-Cube-Solver\hs_err_pid64532.log
>  If you would like to submit a bug report, please visit:   http://bugreport.java.com/bugreport/crash.jsp

**Comment by thatc0der** [comment]
Yes, the position you listed on the puzzle isn't reachable. Is your cube solvable? If the detection fails it could be for one of a few reasons. If you didn't follow the scanning order I showed in the video it will fail. These are the only parameters that can cause this error. Please update me.

**Comment by oguzsh** [comment]
Yep you're right. I tried to scan the cube again with the new hd camera and it worked. Thank you 🥳
